name: Deploy to Github Pages

on:
    push:
        branches: [ main ]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Repository
            uses: actions/checkout@v3
        -   name: Install, build and upload site
            uses: withastro/action@v1
    deploy: 
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: $ {{ steps.deployment.output.page_url }}
        steps:
        -   name: Deploy to Github Pages
            id: deployment
            uses: actions/deploy-pages@v1